routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

Route::group(['middleware' => 'auth'], function () {

	//
	// Profile Routes
	//

	Route::get('settings', function () {
		return view('settings');
	});

	Route::post('settings', ['uses' => 'SettingsController@postSettings']);
	Route::post('settings/delete', ['uses' => 'SettingsController@delete']);

	Route::post('upload/{type}/{id}', ['uses' => 'FileController@upload']);
	Route::delete('file/delete/{id}', ['uses' => 'FileController@delete']);

	Route::get('dashboard', 'DashboardController@index');
	Route::get('social', 'DashboardController@social');
	Route::get('liked', 'DashboardController@liked');
	Route::get('created', 'DashboardController@created');
	Route::get('dashboard/monsters', 'DashboardController@monsters');

	Route::get('profile/{id?}', 'ProfileController@index');

	Route::post('profile/follow/{id}', 'ProfileController@follow');
	Route::post('profile/unfollow/{id}', 'ProfileController@unfollow');

	//
	// Map Routes
	//
	Route::resource('map', 'MapController');

	//
	//Campaign Routes
	//

	Route::resource('campaign', 'CampaignController');
	Route::post('campaign/add/{type}/{id}', 'CampaignController@add');
	Route::post('campaign/batch/{type}', 'CampaignController@batch');
	Route::post('campaign/remove/{type}/{object}', 'CampaignController@detach');
	Route::get('campaign/{id}/{type}', 'CampaignController@view');

	//
	//Player Routes
	//

	Route::resource('character', 'PlayerController');
	Route::resource('player', 'PlayerController');
	Route::get('character/{id}/{key}', ['as' => 'character.private', 'uses' => 'PlayerController@show']);
	Route::post('character/batch/items', 'PlayerController@batchItems');
	Route::post('character/batch/spells', 'PlayerController@batchSpells');
	Route::post('character/prepare/{character}/{spell}', 'PlayerController@prepareSpell');
	Route::get('character/forget/{character}/{spell}', 'PlayerController@forgetSpell');
	Route::post('character/cast/{character}/{slot}', 'PlayerController@incrementSpellCasts');
	Route::post('character/uncast/{character}/{slot}', 'PlayerController@decrementSpellCasts');
	Route::post('character/increment/{character}/{item}', 'PlayerController@incrementItemQuantity');
	Route::post('character/decrement/{character}/{item}', 'PlayerController@decrementItemQuantity');
	Route::post('character/coins/{character}', 'PlayerController@coins');
	Route::post('character/damage/{character}', 'PlayerController@damage');
	Route::post('character/heal/{character}', 'PlayerController@heal');
	Route::post('character/longrest/{character}', 'PlayerController@longRest');

	//
	// Initiative Routes
	//
	Route::resource('combat', 'CombatController');

	//
	// Item Routes
	//

	Route::resource('item', 'ItemController', ['except' => [
		'index', 'show',
	]]);

	Route::post('item/like/{id}', ['as' => 'item.like', 'uses' => 'ItemController@like']);

	Route::get('item/fork/{id}', ['as' => 'item.fork', 'uses' => 'ItemController@fork']);

	//
	// Item Routes
	//

	Route::resource('location', 'LocationController', ['except' => [
		'index', 'show',
	]]);

	Route::post('location/like/{id}', ['as' => 'location.like', 'uses' => 'LocationController@like']);

	Route::get('location/fork/{id}', ['as' => 'location.fork', 'uses' => 'LocationController@fork']);

	//
	// Encounter Routes
	//

	Route::resource('encounter', 'EncounterController', ['except' => [
		'index', 'show',
	]]);

	Route::post('encounter/like/{id}', ['as' => 'encounter.like', 'uses' => 'EncounterController@like']);

	Route::get('encounter/fork/{id}', ['as' => 'encounter.fork', 'uses' => 'EncounterController@fork']);

	//
	// NPC Routes
	//

	Route::resource('npc', 'NpcController', ['except' => [
		'index', 'show',
	]]);

	Route::post('npc/like/{id}', ['as' => 'Npc.like', 'uses' => 'NpcController@like']);

	Route::get('npc/fork/{id}', ['as' => 'Npc.fork', 'uses' => 'NpcController@fork']);

	//
	// Spell Routes
	//
	Route::get('spell/list', ['as' => 'spell.list', 'uses' => 'SpellController@list']);

	Route::resource('spell', 'SpellController');

	Route::get('spell/sort/{type}', ['as' => 'spell.sort', 'uses' => 'SpellController@sort']);
	Route::get('spell/class/{class}', ['as' => 'spell.sortbyclass', 'uses' => 'SpellController@sortByClass']);

	Route::post('spell/get/{name}', 'SpellController@get');

	Route::post('spell/comment/{id}', ['as' => 'spell.comment', 'uses' => 'CommentController@commentSpell']);

	Route::post('spell/like/{id}', ['as' => 'spell.like', 'uses' => 'SpellController@like']);

	Route::get('spell/fork/{id}', ['as' => 'spell.fork', 'uses' => 'SpellController@fork']);

	//
	// Monster Routes
	//

	Route::resource('monster', 'MonsterController', ['except' => [
		'index', 'show',
	]]);

	Route::get('monster/fork/{id}', ['as' => 'monster.fork', 'uses' => 'MonsterController@fork']);

	//
	// Misc Routes
	//

	Route::post('report/{type}/{id}', 'ReportController@store');

	Route::get('comment/delete/{id}', 'CommentController@delete');
	Route::get('note/delete/{id}', 'NoteController@delete');

	Route::get('/logout', 'Auth\LoginController@logout');

	Route::post('/comment/{type}/{id}', ['as' => 'comment', 'uses' => 'CommentController@comment']);
	Route::post('/note/{type}/{id}', ['as' => 'note', 'uses' => 'NoteController@note']);

	Route::post('/like/{type}/{id}', ['as' => 'like', 'uses' => 'LikeController@like']);

	//
	// Notification Routes
	//

	Route::get('notifications', function () {
		Auth::user()->unreadNotifications->markAsRead();
		return view('notifications');
	});

	Route::post('notifications/read', function () {
		Auth::user()->unreadNotifications->markAsRead();
		return response()->json([
			'status' => '200',
		]);
	});

	//
	// Campaign Routes
	//

	Route::resource('journal', 'JournalController', ['except' => [
		'show',
	]]);
});

//
// Authentication Routes
//
Route::auth();

Route::get('login/{provider}', [
	'uses' => 'Auth\LoginController@getSocialAuth',
	'as' => 'auth.getSocialAuth',
]);

Route::get('login/callback/{provider}', [
	'uses' => 'Auth\LoginController@getSocialAuthCallback',
	'as' => 'auth.getSocialAuthCallback',
]);

Route::get('auth/setup/{id}/{provider}', function () {
	return view('auth.setup');
});

Route::post('auth/setup', 'Auth\RegisterController@setup');

//
// Misc Routes
//

Route::get('/', function () {
	if (Auth::check()) {
		return Redirect::to('/dashboard');
	} else {
		return view('landing');
	}
});

Route::get('font', function () {
	return view('font');
});

Route::get('privacy', function () {
	return view('privacy');
});

Route::get('useragreement', function () {
	return view('terms');
});

Route::get('ogl', function () {
	return view('ogl');
});

Route::get('blog', ['uses' => 'BlogController@index']);
Route::get('blog/{slug}', ['uses' => 'BlogController@post']);
//
// Monster Routes
//
Route::get('monster/{id}/{key}', ['as' => 'monster.private', 'uses' => 'MonsterController@show']);
Route::resource('monster', 'MonsterController', ['only' => [
	'index', 'show',
]]);

Route::get('monster/sort/{type}', ['as' => 'monster.sort', 'uses' => 'MonsterController@sort']);
Route::get('monster/tag/{tag}', ['as' => 'monster.tag', 'uses' => 'MonsterController@tag']);

//
// Item Routes
//
Route::get('item/{id}/{key}', ['as' => 'item.private', 'uses' => 'ItemController@show']);
Route::resource('item', 'ItemController', ['only' => [
	'index', 'show',
]]);

Route::get('item/sort/{type}', ['as' => 'item.sort', 'uses' => 'ItemController@sort']);

//
// LocationRoutes
//
Route::get('location/{id}/{key}', ['as' => 'location.private', 'uses' => 'LocationController@show']);
Route::resource('location', 'LocationController', ['only' => [
	'index', 'show',
]]);

Route::get('location/sort/{type}', ['as' => 'location.sort', 'uses' => 'LocationController@sort']);

//
// EncounterRoutes
//
Route::get('encounter/{id}/{key}', ['as' => 'encounter.private', 'uses' => 'EncounterController@show']);
Route::resource('encounter', 'EncounterController', ['only' => [
	'index', 'show',
]]);

Route::get('encounter/sort/{type}', ['as' => 'encounter.sort', 'uses' => 'EncounterController@sort']);

//
// Spell Routes
//
Route::get('spell/{id}/{key}', ['as' => 'spell.private', 'uses' => 'SpellController@show']);
Route::resource('spell', 'SpellController', ['only' => [
	'index', 'show',
]]);

Route::get('spell/sort/{type}', ['as' => 'spell.sort', 'uses' => 'SpellController@sort']);

//
// NPC Routes
//
Route::get('npc/{id}/{key}', ['as' => 'npc.private', 'uses' => 'NpcController@show']);
Route::resource('npc', 'NpcController', ['only' => [
	'index', 'show',
]]);

Route::get('npc/sort/{type}', ['as' => 'npc.sort', 'uses' => 'NpcController@sort']);

//
// Initiative Routes
//
Route::get('combat', 'CombatController@index');

//
// Rules Routes
//
Route::get('rule', 'RuleController@index');
Route::get('rule/{slug}', 'RuleController@show');
Route::get('rule/section/{slug}', 'RuleController@section');

//Route::get('cleanup', 'DashboardController@cleanup');

app/Campaign.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Campaign extends Model
{
    use SoftDeletes;
    
    public function monsters()
    {
        return $this->morphedByMany('App\Monster', 'campaignable')->withTimestamps();
    }

    public function locations()
    {
        return $this->morphedByMany('App\Location', 'campaignable')->withTimestamps();
    }

    public function encounters()
    {
        return $this->morphedByMany('App\Encounter', 'campaignable')->withTimestamps();
    }

    public function npcs()
    {
        return $this->morphedByMany('App\Npc', 'campaignable')->withTimestamps();
    }

    public function items()
    {
        return $this->morphedByMany('App\Item', 'campaignable')->withTimestamps();
    }

    public function players()
    {
        return $this->morphedByMany('App\Player', 'campaignable')->withTimestamps();
    }

    public function journals()
    {
        return $this->hasMany('App\Journal');
    }

    public function user()
    {
        return $this->belongsTo('App\User')->withTimestamps();
    }

    public function files()
    {
        return $this->morphMany('App\File', 'fileable');
    }

}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Campaign;
use App\Http\Requests\StoreCampaign;
use App\Http\Requests\UpdateCampaign;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class CampaignController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$campaigns = \Auth::user()->campaigns;

		return view('campaign.index', compact('campaigns'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('campaign.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(StoreCampaign $request) {
		$campaign = new Campaign();
		$campaign->name = $request->input('name');
		$campaign->user_id = \Auth::id();
		$campaign->save();

		$request->session()->flash('status', 'Your campaign has been added!');

		return redirect('campaign/' . $campaign->id);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		$campaign = Campaign::findOrFail($id);
		$this->authorize('view', $campaign);

		return view('campaign.show', compact('campaign'));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function view($id, $type) {
		$campaign = Campaign::findOrFail($id);

		$this->authorize('view', $campaign);

		if ($type == 'monsters') {
			$campaign->load(['monsters.locations' => function ($query) {
				$query->where('user_id', '=', \Auth::id());
			}]);
			$monsters = Cache::tags(['monsters'])->remember('monsters_list', 60, function () {
				return \App\Monster::pluck('name', 'id');
			});
		} elseif ($type == 'npcs') {
			$campaign->load(['npcs.locations' => function ($query) {
				$query->where('user_id', '=', \Auth::id());
			}]);
			$npcs = Cache::tags(['npcs'])->remember('npcs_list', 60, function () {
				return \App\Npc::pluck('name', 'id');
			});
		} elseif ($type == 'items') {
			$campaign->load(['items.locations' => function ($query) {
				$query->where('user_id', '=', \Auth::id());
			}]);
			$items = Cache::tags(['items'])->remember('items_list', 60, function () {
				return \App\Item::pluck('name', 'id');
			});
		} elseif ($type == 'locations') {
			$locations = Cache::tags(['locations'])->remember('locations_list', 60, function () {
				return \App\Location::pluck('name', 'id');
			});
		}

		return view('campaign.' . $type, compact('campaign', 'monsters', 'items', 'npcs', 'locations'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		$campaign = Campaign::findOrFail($id);

		$this->authorize('update', $campaign);

		return view('campaign.edit', compact('campaign'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(UpdateCampaign $request, $id) {
		$campaign = Campaign::findOrFail($id);

		$this->authorize('update', $campaign);

		$campaign->name = $request->input('name');

		$campaign->update();

		$request->session()->flash('status', 'Your campaign has been edited!');

		return redirect()->action('CampaignController@show', ['id' => $id]);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Request $request, $id) {
		$campaign = Campaign::findOrFail($id);

		$this->authorize('delete', $campaign);

		$campaign->delete();

		// redirect
		$request->session()->flash('status', 'Successfully deleted the campaign!');

		return redirect('campaign');
	}

	public function add(Request $request, $type, $id) {
		$this->validate($request, [
			'campaign' => 'required|numeric',
		]);

		$campaign = Campaign::findOrFail($request->input('campaign'));
		$this->authorize('update', $campaign);

		$relationship = $type . "s";

		$campaign->$relationship()->syncWithoutDetaching([$id]);

		$request->session()->flash('status', 'Successfully added to your campaign!');

		return back();
	}

	public function batch(Request $request, $type) {
		$this->validate($request, [
			'campaign' => 'required|numeric',
			'monsters' => 'array',
			'items' => 'array',
			'locations' => 'array',
			'npcs' => 'array',
		]);

		$campaign = Campaign::findOrFail($request->input('campaign'));
		$this->authorize('update', $campaign);

		if ($request->input('monsters') !== null) {
			foreach ($request->input('monsters') as $monster) {
				$campaign->$type()->syncWithoutDetaching([$monster]);
			}
		} elseif ($request->input('items') !== null) {
			foreach ($request->input('items') as $item) {
				$campaign->$type()->syncWithoutDetaching([$item]);
			}
		} elseif ($request->input('npcs') !== null) {
			foreach ($request->input('npcs') as $npc) {
				$campaign->$type()->syncWithoutDetaching([$npc]);
			}
		} elseif ($request->input('locations') !== null) {
			foreach ($request->input('locations') as $location) {
				$campaign->$type()->syncWithoutDetaching([$location]);
			}
		}

		$request->session()->flash('status', 'Successfully added to your campaign!');

		return back();
	}

	public function detach(Request $request, $type, $object) {
		$this->validate($request, [
			'campaign' => 'required|numeric',
		]);

		$campaign = Campaign::findOrFail($request->input('campaign'));

		$this->authorize('update', $campaign);

		$campaign->$type()->detach($object);

		$request->session()->flash('status', 'Successfully removed from your campaign!');

		return back();
	}
}

resources/views/campaign/create.blade.php
@extends('layouts.app')

@section('title', 'Create a Campaign')

@section('header')
<div class="page-header">
  <div class="ui middle aligned stackable grid container">
    <div class="ui eight wide column">
      <h4 class="ui header">
        Create a Campaign
        <div class="sub header">
          <div class="ui breadcrumb">
            <a href="{{ url('/') }}" class="section">Home</a>
            <i class="right angle icon divider"></i>
            <a href="{{ url('/campaign') }}" class="section">Campaigns</a>
            <i class="right angle icon divider"></i>
            <div class="active section">Create</div>
          </div>
        </div>
      </h4>
    </div>
  </div>
</div>
@endsection

@section('content')
<div class="ui sixteen wide column">
  <form class="ui form" method="POST" action="{{ route('campaign.store') }}">
    {{ csrf_field() }}

    <div class="required field">
      <label>Name</label>
      <input type="text" name="name" placeholder="e.g. Waffle Crew" value="{{ old('name') }}">
    </div>

    <div class="ui clearing hidden divider"></div>
    <button class="ui labeled icon primary fluid button">
      <i class="check icon"></i>
      Save Campaign
    </button>

  </form>
</div>
@endsection

resources/views/campaign/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit a Campaign')

@section('header')
<div class="page-header">
  <div class="ui middle aligned stackable grid container">
    <div class="ui eight wide column">
      <h4 class="ui header">
        Edit {{ $campaign->name }}
        <div class="sub header">
          <div class="ui breadcrumb">
            <a href="{{ url('/') }}" class="section">Home</a>
            <i class="right angle icon divider"></i>
            <a href="{{ url('/campaign') }}" class="section">Campaigns</a>
            <i class="right angle icon divider"></i>
            <div class="active section">Edit</div>
          </div>
        </div>
      </h4>
    </div>
  </div>
</div>
@endsection

@section('content')
<div class="ui sixteen wide column">
  <form class="ui form" method="POST" action="{{ route('campaign.update', $campaign->id) }}">
    {{ csrf_field() }}
    {{ method_field('PUT') }}

    <div class="required field">
      <label>Name</label>
      <input type="text" name="name" placeholder="e.g. Waffle Crew" value="{{ old('name', $campaign->name) }}">
    </div>

    <div class="ui clearing hidden divider"></div>
    <button class="ui labeled icon primary fluid button">
      <i class="check icon"></i>
      Save Campaign
    </button>

  </form>
</div>
@endsection

resources/views/campaign/show.blade.php
@extends('layouts.app')

@section('title', $campaign->name)

@section('header')
<div class="page-header">
  <div class="ui middle aligned stackable grid container">
    <div class="ui sixteen wide column">
      @include('campaign.menu')
    </div>
  </div>
</div>
@endsection

@section('content')
<div class="ui eleven wide column">
  <div class="clearfix">
    <h3 class="ui left floated header">Campaign Journal</h3>
    <div class="ui labeled icon mini right floated primary button" id="journal-create"><i class="write icon"></i>New Entry</div>
  </div>
  <section class="cd-horizontal-timeline">
    <div class="timeline">
      <div class="events-wrapper">
        <div class="events">
          <ol>
            @forelse($campaign->journals->sortBy('created_at') as $journal)
              <li><a href="#0" data-date="{{ $journal->created_at->format('d/m/y\TG:i') }}" @if($loop->last) class="selected" @endif>{{ $journal->created_at->format('M j') }}</a></li>
            @empty
              <li><a href="#0" data-date="{{ date('d/m/y') }}" class="selected">{{ date('M j') }}</a></li>
            @endforelse
          </ol>

          <span class="filling-line" aria-hidden="true"></span>
        </div> <!-- .events -->
      </div> <!-- .events-wrapper -->

      <ul class="cd-timeline-navigation">
        <li><a href="#0" class="prev inactive">Prev</a></li>
        <li><a href="#0" class="next">Next</a></li>
      </ul> <!-- .cd-timeline-navigation -->
    </div> <!-- .timeline -->

    <div class="events-content">
      <ol>
        @forelse($campaign->journals->sortBy('created_at') as $journal)
          <li data-date="{{ $journal->created_at->format('d/m/y\TG:i') }}" @if($loop->last) class="selected" @endif>
            <h2>
              {{ $journal->title }}

              <form action="{{ route('journal.destroy', $journal->id) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
                <button type="submit" class="ui basic icon mini right floated button">
                    <i class="trash icon"></i>
                </button>
              </form>
              <a class="ui basic icon mini right floated button" href="{{ route('journal.edit', $journal->id) }}">
                  <i class="edit icon"></i>
              </a>
            </h2>

            <em>{{ $journal->created_at->format('F j, Y') }} | {{ $journal->elapsed_time }} days elapsed in game</em>
            <span class="journal-body">{!! clean($journal->body) !!}</span>
          </li>
        @empty
          <li data-date="{{ $campaign->created_at->format('d/m/y') }}" class="selected">
            <h2>Welcome!</h2>
            <em>{{ $campaign->created_at->format('F j, Y') }}</em>
            <p>You can use your journal to start tracking what happens each session in your campaign journal.</p>
            <p>Journal entries support a variety of formatting and are a great place to put notes at the end of each session so you never lose track of the finer details.</p>
          </li>
        @endforelse
      </ol>
    </div> <!-- .events-content -->
  </section>
</div>
<div class="ui five wide column">
  <div class="ui fluid card">
    <div class="content">
      <h4 class="ui sub header">Campaign Files</h4>
      <div class="ui small feed">
        @if($campaign->files->isEmpty())
          No files attached.
        @else
          @foreach($campaign->files as $file)
            <div class="event">
              <div class="content">
                <div class="summary">
                   <a href="{{ Storage::url($file->path) }}" target="_blank" class="pull-left">{{ $file->name }}</a>

                   @can('delete', $file)
                   <form action="{{ url('file/delete/'.$file->id) }}" method="POST" class="pull-right">
                     {{ csrf_field() }}
                     {{ method_field('DELETE') }}
                     <button type="submit" class="ui icon compact mini right floated red button">
                         <i class="trash icon"></i>
                     </button>
                   </form>
                   @endcan
                </div>
              </div>
            </div>
          @endforeach
        @endif

      </div>
    </div>
    @can('update', $campaign)
      <div class="extra content text-center">
        <a class="ui mini button" id="upload-modal-trigger">
          <i class="file pdf outline icon"></i>
          Upload PDF or Image
        </a>
      </div>
    @endcan
  </div>

  <div class="ui fluid vertical labeled icon basic buttons">
      @can('update', $campaign)
      <a class="ui button" href="{{ url('campaign/'.$campaign->id.'/edit') }}">
        <i class="edit icon"></i>
        Edit Campaign
      </a>
      @endcan
      @can('delete', $campaign)
      <a class="ui button" id="delete-modal-trigger">
        <i class="remove icon"></i>
        Delete Campaign
      </a>
      @endcan
  </div>

  <div class="ui hidden divider"></div>
</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.0/jquery-migrate.min.js"></script>
<script src="/js/jquery.mobile.custom.min.js"></script>
<script src="/js/timeline.js"></script>

<div class="ui basic modal" id="delete-modal">
  <div class="header">Are you sure?</div>
  <div class="content">
    <p>Deleting the campaign will remove it permanently.</p>
  </div>
  <div class="actions">
    <form action="{{ url('campaign/'.$campaign->id) }}" method="POST">
      {{ csrf_field() }}
      {{ method_field('DELETE') }}
      <div class="ui cancel button">Cancel</div>
      <button type="submit" class="ui red approve button">
          <i class="icon trash"></i>Delete
      </button>
    </form>
  </div>
</div>

<div class="ui modal" id="journal-modal">
  <div class="header">Create a Journal Entry</div>
  <div class="content">
    <form action="{{ route('journal.store') }}" method="POST" class="ui form">
    {{ csrf_field() }}
    <input type="hidden" value="{{ $campaign->id }}" name="campaign_id">
    <div class="field">
      <label for="">Title</label>
      <input type="text" name="title" value="{{ old('title') }}">
    </div>
    <div class="field">
      <textarea name="body" maxlength="5000" class="trumbowyg">{{ old('body') }}</textarea>
    </div>
    <div class="two fields">
      <div class="field">
        <label for="">Date</label>
        <input type="text" data-toggle="datepicker" name="date" value="{{ old('elapsed_time') }}">
      </div>
      <div class="field">
        <label for="">Days Elapsed During Session</label>
        <input type="text" name="elapsed_time" value="{{ old('elapsed_time') }}">
      </div>
    </div>
  </div>
  <div class="actions">
      <div class="ui cancel button">Cancel</div>
      <button type="submit" class="ui green approve button">
          <i class="icon check"></i>Submit
      </button>
    </form>
  </div>
</div>

<div class="ui modal" id="upload-modal">
  <div class="header inline">Choose a file to upload!</div>
  <div class="content">
    <form action="{{ url('upload/campaign', $campaign->id) }}" method="POST" enctype="multipart/form-data" class="ui form">
    {{ csrf_field() }}
    <div class="text-center">
        <input type="file" id="file" name="file" placeholder="Choose a File">
        <label for="file" class="ui icon large button" >
            <i class="file icon"></i>
            Choose a File
        </label>

    </div>
    <p class="text-muted text-center">PDF or image files only. Max file size is 5MB.</p>
  </div>
  <div class="actions">
      <div class="ui cancel button">Cancel</div>
      <button type="submit" class="ui green approve button">
          <i class="icon check"></i>Submit
      </button>
    </form>
  </div>
</div>

<script>

  $('[data-toggle="datepicker"]').datepicker({autoPick:true});

  $('#delete-modal-trigger').click(function(){
      $('#delete-modal').modal('show');
  });
  $('#journal-create').click(function(){
      $('#journal-modal').modal('show');
  });
  $('#upload-modal-trigger').click(function(){
      $('#upload-modal').modal('show');
  });
</script>

@endsection