routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

Route::group(['middleware' => 'auth'], function () {

	//
	// Profile Routes
	//

	Route::get('settings', function () {
		return view('settings');
	});

	Route::post('settings', ['uses' => 'SettingsController@postSettings']);
	Route::post('settings/delete', ['uses' => 'SettingsController@delete']);

	Route::post('upload/{type}/{id}', ['uses' => 'FileController@upload']);
	Route::delete('file/delete/{id}', ['uses' => 'FileController@delete']);

	Route::get('dashboard', 'DashboardController@index');
	Route::get('social', 'DashboardController@social');
	Route::get('liked', 'DashboardController@liked');
	Route::get('created', 'DashboardController@created');
	Route::get('dashboard/monsters', 'DashboardController@monsters');

	Route::get('profile/{id?}', 'ProfileController@index');

	Route::post('profile/follow/{id}', 'ProfileController@follow');
	Route::post('profile/unfollow/{id}', 'ProfileController@unfollow');

	//
	// Map Routes
	//
	Route::resource('map', 'MapController');

	//
	//Campaign Routes
	//

	Route::resource('campaign', 'CampaignController');
	Route::post('campaign/add/{type}/{id}', 'CampaignController@add');
	Route::post('campaign/batch/{type}', 'CampaignController@batch');
	Route::post('campaign/remove/{type}/{object}', 'CampaignController@detach');
	Route::get('campaign/{id}/{type}', 'CampaignController@view');

	//
	//Player Routes
	//

	Route::resource('character', 'PlayerController');
	Route::resource('player', 'PlayerController');
	Route::get('character/{id}/{key}', ['as' => 'character.private', 'uses' => 'PlayerController@show']);
	Route::post('character/batch/items', 'PlayerController@batchItems');
	Route::post('character/batch/spells', 'PlayerController@batchSpells');
	Route::post('character/prepare/{character}/{spell}', 'PlayerController@prepareSpell');
	Route::get('character/forget/{character}/{spell}', 'PlayerController@forgetSpell');
	Route::post('character/cast/{character}/{slot}', 'PlayerController@incrementSpellCasts');
	Route::post('character/uncast/{character}/{slot}', 'PlayerController@decrementSpellCasts');
	Route::post('character/increment/{character}/{item}', 'PlayerController@incrementItemQuantity');
	Route::post('character/decrement/{character}/{item}', 'PlayerController@decrementItemQuantity');
	Route::post('character/coins/{character}', 'PlayerController@coins');
	Route::post('character/damage/{character}', 'PlayerController@damage');
	Route::post('character/heal/{character}', 'PlayerController@heal');
	Route::post('character/longrest/{character}', 'PlayerController@longRest');

	//
	// Initiative Routes
	//
	Route::resource('combat', 'CombatController');

	//
	// Item Routes
	//

	Route::resource('item', 'ItemController', ['except' => [
		'index', 'show',
	]]);

	Route::post('item/like/{id}', ['as' => 'item.like', 'uses' => 'ItemController@like']);

	Route::get('item/fork/{id}', ['as' => 'item.fork', 'uses' => 'ItemController@fork']);

	//
	// Item Routes
	//

	Route::resource('location', 'LocationController', ['except' => [
		'index', 'show',
	]]);

	Route::post('location/like/{id}', ['as' => 'location.like', 'uses' => 'LocationController@like']);

	Route::get('location/fork/{id}', ['as' => 'location.fork', 'uses' => 'LocationController@fork']);

	//
	// Encounter Routes
	//

	Route::resource('encounter', 'EncounterController', ['except' => [
		'index', 'show',
	]]);

	Route::post('encounter/like/{id}', ['as' => 'encounter.like', 'uses' => 'EncounterController@like']);

	Route::get('encounter/fork/{id}', ['as' => 'encounter.fork', 'uses' => 'EncounterController@fork']);

	//
	// NPC Routes
	//

	Route::resource('npc', 'NpcController', ['except' => [
		'index', 'show',
	]]);

	Route::post('npc/like/{id}', ['as' => 'Npc.like', 'uses' => 'NpcController@like']);

	Route::get('npc/fork/{id}', ['as' => 'Npc.fork', 'uses' => 'NpcController@fork']);

	//
	// Spell Routes
	//
	Route::get('spell/list', ['as' => 'spell.list', 'uses' => 'SpellController@list']);

	Route::resource('spell', 'SpellController');

	Route::get('spell/sort/{type}', ['as' => 'spell.sort', 'uses' => 'SpellController@sort']);
	Route::get('spell/class/{class}', ['as' => 'spell.sortbyclass', 'uses' => 'SpellController@sortByClass']);

	Route::post('spell/get/{name}', 'SpellController@get');

	Route::post('spell/comment/{id}', ['as' => 'spell.comment', 'uses' => 'CommentController@commentSpell']);

	Route::post('spell/like/{id}', ['as' => 'spell.like', 'uses' => 'SpellController@like']);

	Route::get('spell/fork/{id}', ['as' => 'spell.fork', 'uses' => 'SpellController@fork']);

	//
	// Monster Routes
	//

	Route::resource('monster', 'MonsterController', ['except' => [
		'index', 'show',
	]]);

	Route::get('monster/fork/{id}', ['as' => 'monster.fork', 'uses' => 'MonsterController@fork']);

	//
	// Misc Routes
	//

	Route::post('report/{type}/{id}', 'ReportController@store');

	Route::get('comment/delete/{id}', 'CommentController@delete');
	Route::get('note/delete/{id}', 'NoteController@delete');

	Route::get('/logout', 'Auth\LoginController@logout');

	Route::post('/comment/{type}/{id}', ['as' => 'comment', 'uses' => 'CommentController@comment']);
	Route::post('/note/{type}/{id}', ['as' => 'note', 'uses' => 'NoteController@note']);

	Route::post('/like/{type}/{id}', ['as' => 'like', 'uses' => 'LikeController@like']);

	//
	// Notification Routes
	//

	Route::get('notifications', function () {
		Auth::user()->unreadNotifications->markAsRead();
		return view('notifications');
	});

	Route::post('notifications/read', function () {
		Auth::user()->unreadNotifications->markAsRead();
		return response()->json([
			'status' => '200',
		]);
	});

	//
	// Campaign Routes
	//

	Route::resource('journal', 'JournalController', ['except' => [
		'show',
	]]);
});

//
// Authentication Routes
//
Route::auth();

Route::get('login/{provider}', [
	'uses' => 'Auth\LoginController@getSocialAuth',
	'as' => 'auth.getSocialAuth',
]);

Route::get('login/callback/{provider}', [
	'uses' => 'Auth\LoginController@getSocialAuthCallback',
	'as' => 'auth.getSocialAuthCallback',
]);

Route::get('auth/setup/{id}/{provider}', function () {
	return view('auth.setup');
});

Route::post('auth/setup', 'Auth\RegisterController@setup');

//
// Misc Routes
//

Route::get('/', function () {
	if (Auth::check()) {
		return Redirect::to('/dashboard');
	} else {
		return view('landing');
	}
});

Route::get('font', function () {
	return view('font');
});

Route::get('privacy', function () {
	return view('privacy');
});

Route::get('useragreement', function () {
	return view('terms');
});

Route::get('ogl', function () {
	return view('ogl');
});

Route::get('blog', ['uses' => 'BlogController@index']);
Route::get('blog/{slug}', ['uses' => 'BlogController@post']);
//
// Monster Routes
//
Route::get('monster/{id}/{key}', ['as' => 'monster.private', 'uses' => 'MonsterController@show']);
Route::resource('monster', 'MonsterController', ['only' => [
	'index', 'show',
]]);

Route::get('monster/sort/{type}', ['as' => 'monster.sort', 'uses' => 'MonsterController@sort']);
Route::get('monster/tag/{tag}', ['as' => 'monster.tag', 'uses' => 'MonsterController@tag']);

//
// Item Routes
//
Route::get('item/{id}/{key}', ['as' => 'item.private', 'uses' => 'ItemController@show']);
Route::resource('item', 'ItemController', ['only' => [
	'index', 'show',
]]);

Route::get('item/sort/{type}', ['as' => 'item.sort', 'uses' => 'ItemController@sort']);

//
// LocationRoutes
//
Route::get('location/{id}/{key}', ['as' => 'location.private', 'uses' => 'LocationController@show']);
Route::resource('location', 'LocationController', ['only' => [
	'index', 'show',
]]);

Route::get('location/sort/{type}', ['as' => 'location.sort', 'uses' => 'LocationController@sort']);

//
// EncounterRoutes
//
Route::get('encounter/{id}/{key}', ['as' => 'encounter.private', 'uses' => 'EncounterController@show']);
Route::resource('encounter', 'EncounterController', ['only' => [
	'index', 'show',
]]);

Route::get('encounter/sort/{type}', ['as' => 'encounter.sort', 'uses' => 'EncounterController@sort']);

//
// Spell Routes
//
Route::get('spell/{id}/{key}', ['as' => 'spell.private', 'uses' => 'SpellController@show']);
Route::resource('spell', 'SpellController', ['only' => [
	'index', 'show',
]]);

Route::get('spell/sort/{type}', ['as' => 'spell.sort', 'uses' => 'SpellController@sort']);

//
// NPC Routes
//
Route::get('npc/{id}/{key}', ['as' => 'npc.private', 'uses' => 'NpcController@show']);
Route::resource('npc', 'NpcController', ['only' => [
	'index', 'show',
]]);

Route::get('npc/sort/{type}', ['as' => 'npc.sort', 'uses' => 'NpcController@sort']);

//
// Initiative Routes
//
Route::get('combat', 'CombatController@index');

//
// Rules Routes
//
Route::get('rule', 'RuleController@index');
Route::get('rule/{slug}', 'RuleController@show');
Route::get('rule/section/{slug}', 'RuleController@section');

//Route::get('cleanup', 'DashboardController@cleanup');

app/Location.php
<?php

namespace App;

use Cartalyst\Tags\TaggableInterface;
use Cartalyst\Tags\TaggableTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;

class Location extends Model implements TaggableInterface {
	use SoftDeletes;
	use Searchable;
	use TaggableTrait;

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */

	protected $dates = ['deleted_at'];

	protected $guarded = ['id', 'user_id', 'created_at', 'updated_at', 'deleted_at'];

	public function toSearchableArray() {

		$data['id'] = $this->id;
		$data['name'] = $this->name;
		$data['description'] = $this->description;
		$data['type'] = $this->type;
		$data['subtype'] = $this->subtype;
		$data['created_at'] = $this->created_at;
		$data['source'] = $this->source;
		$data['view_count'] = $this->view_count;
		$data['like_count'] = $this->like_count;
		$data['user_name'] = $this->user->name;
		$data['user_id'] = $this->user->id;
		$data['user_avatar'] = $this->user->avatar;
		$data['description_short'] = str_limit(strip_tags($this->description), 240);
		$data['comment_count'] = $this->comments->count();
		if ($this->private != 1) {
			$data['_tags'] = ['user_' . $this->user->id, 'public'];
		} else {
			$data['_tags'] = ['user_' . $this->user->id];
		}

		return $data;
	}

	public function likes() {
		return $this->morphMany('App\Like', 'likeable');
	}

	public function files() {
		return $this->morphMany('App\File', 'fileable');
	}

	public function comments() {
		return $this->morphMany('App\Comment', 'commentable');
	}

	public function private_notes() {
		return $this->morphMany('App\Note', 'noteable');
	}

	public function campaigns() {
		return $this->morphToMany('App\Campaign', 'campaignable');
	}

	public function root() {
		return $this->where('id', $this->parent)->first();
	}

	public function children() {
		return $this->where('parent', $this->id)->get();
	}

	public function forkedFrom() {
		return $this->belongsTo('App\Location', 'fork_id');
	}

	public function forkedTo() {
		return $this->hasMany('App\Location', 'fork_id');
	}

	public function getIsLikedAttribute() {
		$like = $this->likes()->whereUserId(\Auth::id())->first();
		return (!is_null($like)) ? true : false;
	}

	public function user() {
		return $this->belongsTo('App\User')->withTrashed();
	}

	public function monsters() {
		return $this->belongsToMany('App\Monster', 'location_monsters', 'location_id', 'monster_id');
	}

	public function items() {
		return $this->belongsToMany('App\Item', 'location_items', 'location_id', 'item_id');
	}

	public function npcs() {
		return $this->belongsToMany('App\Npc', 'location_npcs', 'location_id', 'npc_id');
	}
}

resources/views/location/create.blade.php
@extends('layouts.app')

@section('title', 'Create a Location')

@section('header')
<div class="page-header">
  <div class="ui middle aligned stackable grid container">
    <div class="ui sixteen wide column">
      <h4 class="ui header">
        Create a Location
        <div class="sub header">
          <div class="ui breadcrumb">
            <a href="{{ url('/') }}" class="section">Home</a>
            <i class="right angle icon divider"></i>
            <a href="{{ url('/location') }}" class="section">Locations</a>
            <i class="right angle icon divider"></i>
            <div class="active section">Create</div>
          </div>
        </div>
      </h4>
    </div>
  </div>
</div>
@endsection

@section('content')
<div class="ui sixteen wide column">
  @include('location.form')
</div>
@endsection

@section('scripts')
<script>
$(document).ready(function()
{

  $('.ui.search.dropdown.tags')
    .dropdown({
      allowAdditions: true
    });

  $('#type').change(function(){
    $('.subtypes').hide();
    if($(this).val() == 'Shop'){
      $('#shop').show();
    }else if($(this).val() == 'Village/Town/City' || $(this).val() == 'Continent' || $(this).val() == 'Kingdom'){
      $('#city').show();
    }else if($(this).val() == 'Tavern/Inn'){
      $('#tavern').show();
    }
  });

  $('.popup').popup();
});
</script>
@endsection

resources/views/location/edit.blade.php
@extends('layouts.app')

@section('title', $location->name)

@section('header')
<div class="page-header">
  <div class="ui middle aligned stackable grid container">
    <div class="ui sixteen wide column">
      <h4 class="ui header">
        {{ Request::is('location/fork/*') ? "Create":"Edit" }} a Location
        <div class="sub header">
          <div class="ui breadcrumb">
            <a href="{{ url('/') }}" class="section">Home</a>
            <i class="right angle icon divider"></i>
            <a href="{{ url('/location') }}" class="section">Locations</a>
            <i class="right angle icon divider"></i>
            <a href="{{ url('/location/'.$location->id) }}" class="section">{{ $location->name }}</a>
            <i class="right angle icon divider"></i>
            <div class="active section">{{ Request::is('location/fork/*') ? "Create":"Edit" }}</div>
          </div>
        </div>
      </h4>
    </div>
  </div>
</div>
@endsection

@section('content')
<div class="ui sixteen wide column">
  @include('location.form')
</div>
@endsection

@section('scripts')
<script>
$(document).ready(function()
{

  $('.ui.search.dropdown.tags')
    .dropdown({
      allowAdditions: true
    });

    if($('#type').val() == 'Shop'){
      $('#shop').show();
    }else if($('#type').val() == 'Village/Town/City' || $('#type').val() == 'Continent' || $('#type').val() == 'Kingdom'){
      $('#city').show();
    }else if($('#type').val() == 'Tavern/Inn'){
      $('#tavern').show();
    }

    $('#type').change(function(){
    $('.subtypes').hide();
      if($(this).val() == 'Shop'){
        $('#shop').show();
      }else if($(this).val() == 'Village/Town/City' || $(this).val() == 'Continent' || $(this).val() == 'Kingdom'){
        $('#city').show();
      }else if($(this).val() == 'Tavern/Inn'){
        $('#tavern').show();
      }
    });

  $('.popup').popup();
});
</script>
@endsection

resources/views/location/edit_form.blade.php
<form class="ui form" method="POST" action="@if(Route::currentRouteAction() == 'App\Http\Controllers\LocationController@edit') {{  route('location.update', $location->id) }} @else {{ route('location.store') }} @endif">

  {{ csrf_field() }}

  @if(Route::currentRouteAction() == 'App\Http\Controllers\LocationController@edit')
    {{ method_field('PUT') }}
  @endif

  @if(Request::is('location/fork/*'))
    <input type="hidden" name="fork_id" value="{{ $location->id }}">
  @endif

  <div class="two fields">

    <div class="required field">
      <label>Name</label>
      <input type="text" name="name" placeholder="e.g. Annie's Armor, Frostspine Peaks, etc" value="{{ old('name', $location->name) }}">
    </div>

    <div class="required field">
      <label>Type</label>
      <select name="type" class="ui compact dropdown" id="type">
        @if(!old("type", $location->type))
          <option value="" disabled selected>None</option>
        @endif
        @foreach (Config::get('constants.location_types') as $key => $value)
            <option value="{{ $value }}" {{ ($value == old('type', $location->type)) ? "selected":"" }}>{{ $value }}</option>
        @endforeach
      </select>
    </div>

  </div>

  <div class="field">
    <label>Does this location belong to another location?</label>
    <div class="ui fluid input">
      <select class="ui fluid search dropdown" name="parent">
        <option value="0">None</option>
        @foreach($locations as $place)
          <option value="{{ $place->id }}" {{ old('parent', $location->parent) == $place->id ? "selected":"" }}>{{ $place->name }}</option>
        @endforeach
      </select>
    </div>
  </div>

  <div class="subtypes" id="shop" @if(old('type', $location->type) != "Shop")style="display:none;"@endif>
    <h4 class="ui dividing header">Shop Details</h4>

    <div class="two fields">
      <div class="field">
        <label>Subtype</label>
        <select name="subtype" class="ui compact dropdown">
          @if(!old("subtype"))
            <option value="" disabled selected>None</option>
          @endif
          @foreach (Config::get('constants.location_shop_types') as $key => $value)
              <option value="{{ $value }}" {{ ($value == old('subtype', $location->subtype)) ? "selected":"" }}>{{ $value }}</option>
          @endforeach
        </select>
      </div>
      <div class="field">
        <label>Owner</label>
        <input type="text" name="owner" placeholder="e.g. Annie Irongrip" value="{{ old('owner', $location->owner) }}">
      </div>
    </div>

    <div class="field">
      <label for="">What does the shop sell?</label>
      <span class="sub-label">To make a list of what the shop sells, use the Linking section later in the form.</span>
    </div>

    <div class="field">
      <label for="">Other Items</label>
      <textarea rows="2" name="other_items" placeholder="e.g. gems, tools, or any other items that may not deserve creating their own record.">{{ old('other_items', $location->other_items) }}</textarea>
    </div>
  </div>

  <div class="subtypes" id="city" @if(old('type', $location->type) != "Village/Town/City" || old('type') != "Continent" || old('type') != "Kingdom")style="display:none;"@endif>

    <h4 class="ui dividing header">City Details</h4>

    <div class="field">
      <label for="">Demographics</label>
      <textarea rows="2" name="demographics" placeholder="e.g. The city is mostly run by the wood elves that established it. However, the port district is majority dwarf sailors...">{{ old('demographics', $location->demographics) }}</textarea>
    </div>

    <div class="field">
      <label for="">Government</label>
      <textarea rows="2" name="government" placeholder="e.g. The city uses a democracy where the citizens with the most wealth are able to buy more votes. The funds from the purchased votes go towards community efforts.">{{ old('government', $location->government) }}</textarea>
    </div>
  </div>

  <div class="subtypes" id="tavern" @if(old('type', $location->type) != "Tavern/Inn")style="display:none;"@endif>
    <h4 class="ui dividing header">Tavern Details</h4>

    <div class="two fields">
      <div class="field">
        <label>Room Price</label>
        <input type="text" name="price" placeholder="e.g. 50 SP per night, 1 GP luxury room" value="{{ old('price', $location->price) }}">
      </div>
      <div class="field">
        <label>Owner</label>
        <input type="text" name="owner_tavern" placeholder="e.g. Luthar Silverglint" value="@if($location->type == 'Tavern/Inn'){{$location->owner}}@else{{old('owner_tavern')}}@endif">
      </div>
    </div>

    <div class="field">
      <label for="">Food/Drinks</label>
      <textarea rows="2" name="menu" placeholder="e.g. basilisk eye stew, luthar's special reserve, etc. ">{{ old('menu', $location->menu) }}</textarea>
    </div>
  </div>

  <h4 class="ui dividing header">Description & History</h4>

  <div class="required field">
    <label for="">Description</label>
    <div class="sub-label"><small>Tip: Use the Quote option to display descriptive/read aloud text callouts. To end the quote, select the Paragraph option again.</small></div>
    <textarea rows="4" name="description" placeholder="" class="trumbowyg">{{ old('description', $location->description) }}</textarea>
  </div>

  <h4 class="ui dividing header">Link NPCs, Monsters & Items</h4>

  <div class="field">
    <div class="sub-label">Linking items to this location will provide quick look stats and convenient links to quickly access content.</div>
  </div>

  <div class="field">
    <label>Do any notable NPCs hang out at this location?</label>
    <span class="sub-label"><small>Don't see an NPC you like? <a href="{{ url('npc/create') }}" target="_blank">Create your own!</a></small></span>
    <select class="ui fluid search dropdown" multiple="" name="npcs[]">
      @foreach($npcs as $npc)
        <option value="{{ $npc->id }}" {{ ((is_array(old('npcs', $selected_npcs)) && in_array($npc->id, old('npcs', $selected_npcs))) ? "selected":"") }}>{{ $npc->name }}</option>
      @endforeach
    </select>
  </div>

  <div class="field">
    <label>Do any notable monsters roam this location?</label>
    <span class="sub-label"><small>Don't see a monster you like? <a href="{{ url('monster/create') }}" target="_blank">Create your own!</a></small></span>
    <select class="ui fluid search dropdown" multiple="" name="monsters[]">
      @foreach($monsters as $monster)
        <option value="{{ $monster->id }}" {{ ((is_array(old('monsters', $selected_monsters)) && in_array($monster->id, old('monsters', $selected_monsters))) ? "selected":"") }}>{{ $monster->name }}</option>
      @endforeach
    </select>
  </div>

  <div class="field">
    <label>What does the shop sell or what magic items can be found here?</label>
    <span class="sub-label"><small>Don't see an item you like? <a href="{{ url('item/create') }}" target="_blank">Create your own!</a></small></span>
    <select class="ui fluid search dropdown" multiple="" name="items[]">
      @foreach($items as $item)
        <option value="{{ $item->id }}" {{ ((is_array(old('items')) && in_array($item->id, old('items'))) ? "selected":"") }}>{{ $item->name }}</option>
      @endforeach
    </select>
  </div>

  <h4 class="ui dividing header">Tags</h4>
  <div class="field">
    <label for="tags">Tags (type + enter to add tags)</label>
    <select class="ui fluid search dropdown" multiple="" name="tags[]" id="tags">
      @if(old('tags'))
        @for($i = 0; $i < count(old('tags')); $i++)
          <option value="{{ old('tags.'.$i) }}" selected>{{ old('tags.'.$i) }}</option>
        @endfor
        @foreach($tags as $tag)
          @if(!in_array($tag->name, old('tags')))
            <option value="{{ $tag->name }}" {{ (is_array($location->tags) && in_array($tag, $location->tags)) ? "selected":"" }}>{{ $tag }}</option>
          @endif
        @endforeach
      @else
        @foreach($tags as $tag)
          <option value="{{ $tag->name }}" {{ $location->tags->contains('name', $tag->name) ? "selected":"" }}>{{ $tag->name }}</option>
        @endforeach
      @endif
    </select>
  </div>


  <div class="ui clearing hidden divider"></div>
  <h4 class="ui dividing header">Visibility</h4>
  <div class="ui toggle checkbox">
    <input type="checkbox" name="private" value="1" @if(old('private', $location->private)) checked @endif>
    <label>Make this location private. This prevents other users from seeing it in the index or search results.</label>
  </div>
  <div class="ui clearing hidden divider"></div>
  <div class="ui clearing hidden divider"></div>

  <button class="ui labeled icon primary fluid button">
    <i class="check icon"></i>
    Save Location
  </button>

</form>

resources/views/location/snippet.blade.php
<div class='ui list'>
	<div class='item'>
		<div class='header'>
			Level/School
		</div>		
		{{ $spell->level }} {{ $spell->school }}
	</div>
	<div class='item'>
		<div class='header'>
			Cast Time
		</div>		
		{{ $spell->casting_time }}
	</div>
	<div class='item'>
		<div class='header'>
			Range
		</div>		
		{{ $spell->range }}
	</div>
	<div class='item'>
		<div class='header'>
			Component
		</div>
		{{ $spell->components }}		
	</div>
	<div class='item'>
		<div class='header'>
			Duration
		</div>
		{{ $spell->duration }}		
	</div>
	<div class='item'>
		<div class='header'>
			Materials
		</div>
		{{ $spell->material }}		
	</div>
	<div class='item'>
		<div class='header'>
			Concentration/Ritual
		</div>
		{{ ($spell->concentration == 1) ? 'yes' : 'no' }}	/ {{ ($spell->ritual == 1) ? 'yes' : 'no' }}	
	</div>
	<div class='item'>
		{{ $spell->description}}		
	</div>
</div>